language: ruby
before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - bundle exec rake test_app
script:
  - bundle exec rspec spec
notifications:
  email:
    - tiagocis@gmail.com
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
branches:
  only:
    - 2-1-stable
    - 2-2-stable