branches:
  only:
    - master
		- 1-3-stable
		- 2-0-stable
rvm:
  - 1.9.2
  - 1.9.3

before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "bundle exec dummier"

script: "DISPLAY=:99.0 bundle exec rake"
